### ISSUE TITLE
"TypeError: Cannot read property 'dirty' of null" when using ngxErrors inside formArrayName

### ISSUE THREAD

**Issue by beltschatsar** [UltimateAngular/ngx-errors#27]
**Is this a feature request or a bug report?**
bug

**What's gone wrong?**
When trying to add an ngxerrors/ngxerror for a required field inside a formArrayName, it give a "TypeError: Cannot read property 'dirty' of null". It isn't clear for me how to refer to the current array instance since `<div ngxErrors="stock[i].quantity">` doesn't seems to work.
[this](https://github.com/UltimateAngular/ngx-errors#nested-formgroup-supportl) introduce de dot notation for refering to a control inside a FormGroup, but no reference to a [] syntax for a control inside a FormArray.

**What was meant to happen?**
No errors expected since no user interaction begin

**Steps to reproduce**
Steps used to reproduce the problem:

1. Clone https://github.com/UltimateAngular/ngx-errors.git (do `yarn install` after)

2.  In example/app/stock-inventory/components/stock-products/stock-products.component.ts, before line 28 add the following:
`            <div ngxErrors="stock[i].quantity">
              <div class="error" ngxError="required" [when]="['dirty']">
                Field is required
              </div>
            </div>
`
as shown: 
![step-2](https://user-images.githubusercontent.com/30058609/28073179-ff44cf5c-6622-11e7-90e2-9dfbaefb18b8.png)

3. In example/app/stock-inventory/containers/stock-inventory/stock-products.component.ts, replace line 73 by:
`    stock: this.fb.array([
      this.createStock({product_id:1, quantity: 1 })
      ], Validators.required)
`
as shown: 
![step-3](https://user-images.githubusercontent.com/30058609/28073180-011027e6-6623-11e7-9c6d-4af3908b441f.png)

4. run `npm run example `. In chrome console (F12), you should see the following:
`HMR] Waiting for update signal from WDS...
ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:297 ERROR TypeError: Cannot read property 'dirty' of null
    at http://localhost:3000/build/app.js:766:93
    at Array.filter (native)
    at NgxErrorDirective.webpackJsonp../src/ngxerror.directive.ts.NgxErrorDirective.ngDoCheck (http://localhost:3000/build/app.js:766:38)
    at checkAndUpdateDirectiveInline (http://localhost:3000/build/vendor.js:42357:19)
    at checkAndUpdateNodeInline (http://localhost:3000/build/vendor.js:43733:17)
    at checkAndUpdateNode (http://localhost:3000/build/vendor.js:43701:16)
    at debugCheckAndUpdateNode (http://localhost:3000/build/vendor.js:44330:59)
    at debugCheckDirectivesFn (http://localhost:3000/build/vendor.js:44271:13)
    at Object.View_StockProductsComponent_1.co [as updateDirectives] (ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:373:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:3000/build/vendor.js:44256:21)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43668:14)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
    at execEmbeddedViewsAction (http://localhost:3000/build/vendor.js:43955:17)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43669:5)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
View_StockProductsComponent_1 @ ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:297
ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:297 ERROR CONTEXT DebugContext_
View_StockProductsComponent_1 @ ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:297
ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:297 ERROR TypeError: Cannot read property 'dirty' of null
    at http://localhost:3000/build/app.js:766:93
    at Array.filter (native)
    at NgxErrorDirective.webpackJsonp../src/ngxerror.directive.ts.NgxErrorDirective.ngDoCheck (http://localhost:3000/build/app.js:766:38)
    at checkAndUpdateDirectiveInline (http://localhost:3000/build/vendor.js:42357:19)
    at checkAndUpdateNodeInline (http://localhost:3000/build/vendor.js:43733:17)
    at checkAndUpdateNode (http://localhost:3000/build/vendor.js:43701:16)
    at debugCheckAndUpdateNode (http://localhost:3000/build/vendor.js:44330:59)
    at debugCheckDirectivesFn (http://localhost:3000/build/vendor.js:44271:13)
    at Object.View_StockProductsComponent_1.co [as updateDirectives] (ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:373:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:3000/build/vendor.js:44256:21)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43668:14)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
    at execEmbeddedViewsAction (http://localhost:3000/build/vendor.js:43955:17)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43669:5)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
View_StockProductsComponent_1 @ ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:297
ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:297 ERROR CONTEXT DebugContext_
View_StockProductsComponent_1 @ ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:297
vendor.js:72762 Unhandled Promise rejection: Cannot read property 'dirty' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'dirty' of null
    at http://localhost:3000/build/app.js:766:93
    at Array.filter (native)
    at NgxErrorDirective.webpackJsonp../src/ngxerror.directive.ts.NgxErrorDirective.ngDoCheck (http://localhost:3000/build/app.js:766:38)
    at checkAndUpdateDirectiveInline (http://localhost:3000/build/vendor.js:42357:19)
    at checkAndUpdateNodeInline (http://localhost:3000/build/vendor.js:43733:17)
    at checkAndUpdateNode (http://localhost:3000/build/vendor.js:43701:16)
    at debugCheckAndUpdateNode (http://localhost:3000/build/vendor.js:44330:59)
    at debugCheckDirectivesFn (http://localhost:3000/build/vendor.js:44271:13)
    at Object.View_StockProductsComponent_1.co [as updateDirectives] (ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:373:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:3000/build/vendor.js:44256:21)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43668:14)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
    at execEmbeddedViewsAction (http://localhost:3000/build/vendor.js:43955:17)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43669:5)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17) TypeError: Cannot read property 'dirty' of null
    at http://localhost:3000/build/app.js:766:93
    at Array.filter (native)
    at NgxErrorDirective.webpackJsonp../src/ngxerror.directive.ts.NgxErrorDirective.ngDoCheck (http://localhost:3000/build/app.js:766:38)
    at checkAndUpdateDirectiveInline (http://localhost:3000/build/vendor.js:42357:19)
    at checkAndUpdateNodeInline (http://localhost:3000/build/vendor.js:43733:17)
    at checkAndUpdateNode (http://localhost:3000/build/vendor.js:43701:16)
    at debugCheckAndUpdateNode (http://localhost:3000/build/vendor.js:44330:59)
    at debugCheckDirectivesFn (http://localhost:3000/build/vendor.js:44271:13)
    at Object.View_StockProductsComponent_1.co [as updateDirectives] (ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:373:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:3000/build/vendor.js:44256:21)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43668:14)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
    at execEmbeddedViewsAction (http://localhost:3000/build/vendor.js:43955:17)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43669:5)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
consoleError @ vendor.js:72762
vendor.js:72764 Error: Uncaught (in promise): TypeError: Cannot read property 'dirty' of null
TypeError: Cannot read property 'dirty' of null
    at http://localhost:3000/build/app.js:766:93
    at Array.filter (native)
    at NgxErrorDirective.webpackJsonp../src/ngxerror.directive.ts.NgxErrorDirective.ngDoCheck (http://localhost:3000/build/app.js:766:38)
    at checkAndUpdateDirectiveInline (http://localhost:3000/build/vendor.js:42357:19)
    at checkAndUpdateNodeInline (http://localhost:3000/build/vendor.js:43733:17)
    at checkAndUpdateNode (http://localhost:3000/build/vendor.js:43701:16)
    at debugCheckAndUpdateNode (http://localhost:3000/build/vendor.js:44330:59)
    at debugCheckDirectivesFn (http://localhost:3000/build/vendor.js:44271:13)
    at Object.View_StockProductsComponent_1.co [as updateDirectives] (ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:373:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:3000/build/vendor.js:44256:21)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43668:14)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
    at execEmbeddedViewsAction (http://localhost:3000/build/vendor.js:43955:17)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43669:5)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
    at http://localhost:3000/build/app.js:766:93
    at Array.filter (native)
    at NgxErrorDirective.webpackJsonp../src/ngxerror.directive.ts.NgxErrorDirective.ngDoCheck (http://localhost:3000/build/app.js:766:38)
    at checkAndUpdateDirectiveInline (http://localhost:3000/build/vendor.js:42357:19)
    at checkAndUpdateNodeInline (http://localhost:3000/build/vendor.js:43733:17)
    at checkAndUpdateNode (http://localhost:3000/build/vendor.js:43701:16)
    at debugCheckAndUpdateNode (http://localhost:3000/build/vendor.js:44330:59)
    at debugCheckDirectivesFn (http://localhost:3000/build/vendor.js:44271:13)
    at Object.View_StockProductsComponent_1.co [as updateDirectives] (ng:///StockInventoryModule/StockProductsComponent.ngfactory.js:373:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:3000/build/vendor.js:44256:21)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43668:14)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
    at execEmbeddedViewsAction (http://localhost:3000/build/vendor.js:43955:17)
    at checkAndUpdateView (http://localhost:3000/build/vendor.js:43669:5)
    at callViewAction (http://localhost:3000/build/vendor.js:43983:17)
    at resolvePromise (http://localhost:3000/build/vendor.js:72905:31) [<root>]
    at http://localhost:3000/build/vendor.js:72831:17 [<root>]
    at http://localhost:3000/build/vendor.js:72847:33 [<root>]
    at http://localhost:3000/build/vendor.js:72953:57 [<root>]
    at drainMicroTaskQueue (http://localhost:3000/build/vendor.js:72786:35) [<root>]
consoleError @ vendor.js:72764
vendor.js:71691 [WDS] Hot Module Replacement enabled.
`
as shown: 
![step-4](https://user-images.githubusercontent.com/30058609/28073185-026aca56-6623-11e7-892d-433e765a0010.png)

**Other information**
vsc Version 1.13.1 in Xubuntu 16.04 LTS (amd64) (runned from a windows 10 host in VirtualBox).
node 8.1.2
npm 5.0.3
yarn 0.23.4

Thanks for this great package!

**Comment by AncelHernandez** [comment]
+1 I also have this issue

**Comment by friend-ship** [comment]
I alse met this problem

**Comment by mderriey** [comment]
I had this issue too, and got around it by using the dot notation to access each form group in the form array.

```ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormArray, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-form-array',
  templateUrl: './form-array.component.html',
  styleUrls: ['./form-array.component.scss']
})
export class FormArraysComponent implements OnInit {

  form: FormGroup;

  constructor() { }

  ngOnInit() {
    this.form = new FormGroup({
      array: new FormArray(
        [this.createItem()]
      )
    });
  }

  get array(): FormArray {
    return this.form.get('array') as FormArray;
  }

  private createItem(
    name: string = '',
    hobby: string = ''
  ): FormGroup {
    return new FormGroup({
      name: new FormControl(name, Validators.required),
      hobby: new FormControl(hobby, Validators.required)
    });
  }
}
```

```html
<form [formGroup]="form">
  <div formArrayName="array">
    <div *ngFor="let item of array.controls; let i = index" [formGroupName]="i">
      <div class="form-group col-4">
        <label for="name-{{i}}">Name</label>
        <input type="text" id="name-{{i}}" class="form-control" formControlName="name">
        <span ngxError="required" [ngxErrors]="['array', i, 'name']" class="invalid-feedback">
          Name is required
        </span>
      </div>

      <div class="form-group col-4">
        <label for="hobby-{{i}}">Hobby</label>
        <input type="text" id="hobby-{{i}}" class="form-control" formControlName="hobby">
        <span ngxError="required" [ngxErrors]="['array', i, 'hobby']" class="invalid-feedback">
          Hobby is required
        </span>
      </div>
    </div>
  </div>
</form>
```

The important bit is that what is passed to the `ngxErrors` directive will be used as a parameter to the [`get` method of `AbstractControl`](https://github.com/angular/angular/blob/0038712474cbc61f36dac10d43c6e7ab48929b4e/packages/forms/src/model.ts#L494-L507).
