### ISSUE TITLE
Unexpected token import - angular universal

### ISSUE THREAD

**Issue by lomboboo** [UltimateAngular/ngx-errors#42]
**Issue report**

**What's gone wrong?**
So I have Angular 4 + Angular Universal app and I'm using your awesome plugin. But during server compilation I' getting this nasty error:
```
***/client/node_modules/@ultimate/ngxerrors/src/ngxerror.directive.js:1
(function (exports, require, module, __filename, __dirname) { import { Directive, Input, Inject, HostBinding, forwardRef } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (*/client/dist/ngfactory/src/app/register/register.component.ngfactory.ts:11:1)
    at Module._compile (module.js:570:32)

```

**Steps to reproduce**

**Server.ts:**
```
import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import { platformServer, renderModuleFactory } from '@angular/platform-server'
import { enableProdMode } from '@angular/core'
import { AppServerModuleNgFactory } from '../dist/ngfactory/src/app/app.server.module.ngfactory'
import * as express from 'express';
import { readFileSync } from 'fs';
import { join } from 'path';

const PORT = 3000;

enableProdMode();

const app = express();

let template = readFileSync(join(__dirname, '..', 'dist', 'index.html')).toString();

app.engine('html', (_, options, callback) => {
	const opts = { document: template, url: options.req.url };

	renderModuleFactory(AppServerModuleNgFactory, opts)
		.then(html => callback(null, html));
});

app.set('view engine', 'html');
app.set('views', 'src');

app.get('*.*', express.static(join(__dirname, '..', 'dist')));

app.get('*', (req, res) => {
	res.render('index', { req });
});

app.listen(PORT, () => {
	console.log(`listening on http://localhost:${PORT}!`);
});
```
**app.server.module.ts**
```
import { NgModule } from '@angular/core';
import { ServerModule } from '@angular/platform-server';
import { AppModule } from './app.module';
import { AppComponent } from './app.component';

@NgModule({
	imports: [
		ServerModule,
		AppModule
	],
	bootstrap: [AppComponent]
})
export class AppServerModule { }
```

**Other information**
Ubuntu 16, Node v.6.9.2, Angular 4.2.4

**Comment by khurshedt9l** [comment]
Hi @lomboboo ,
I am facing same issue. Hopefully you have solved this issue. Can you help me

**Comment by Stevertus** [comment]
+1

**Comment by lomboboo** [comment]
@khurshedt9l , @Stevertus 
yes, I ended up with compiling this module to es5. I described my solution [here](https://github.com/SebastianM/angular-google-maps/issues/1052#issuecomment-346992312)
